forbid symlinks pointing to themselves

diff --git a/brp-25-symlink b/brp-25-symlink
--- a/brp-25-symlink
+++ b/brp-25-symlink
@@ -79,6 +79,11 @@ do
 	fi
     done
 
+    if test "$link" = "$link_dest"; then
+      echo "ERROR: $link points to itself (as $orig_link_dest)"
+      exit 1
+    fi
+
     # black list
     case "$link,$link_dest" in
 	*,/var/lib/named*)
